In [2]:
import numpy as np
from scipy.sparse import coo_matrix
from scipy.sparse import csr_matrix
import matplotlib.pyplot as plt

#BFS using FIFO queue
from queue import Queue,LifoQueue,PriorityQueue
from collections import defaultdict 
##
import networkx as nx
import scipy.stats as stats
import scipy.sparse as sparse

In [3]:

# Load the data

# See http://docs.scipy.org/doc/numpy/user/basics.io.genfromtxt.html

# data = np.loadtxt('E:\研一下学期资料\CPE800\It_can_work\toy.dat', delimiter=',')

data = np.fromfile('E:\\研一下学期资料\\CPE800\\It_can_work\\toy.txt',dtype=np.int,sep=' ')


# Examine data

print(data.shape)


(26,)


In [4]:
len(data)

26

In [5]:
sourse = []
target = []
for i in range(13):
#     print(i)
    sourse.append(data[i*2])
    
    target.append(data[i*2+1])
    print(target[i])

1
4
2
2
7
7
5
3
5
6
8
8
9


In [6]:
sourse = np.array(sourse)
target = np.array(target)
v=[]
for i in range(13):
    v.append(8)
value = np.array(v)  # useless but needed

In [7]:
origional = coo_matrix((value, (sourse, target)), shape=(13, 13)).toarray()
# origional[0][1]
origional

array([[0, 8, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 8, 0, 8, 0, 8, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 8, 8, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [8]:
CSR = coo_matrix((value, (sourse, target)), shape=(13, 13)).tocsr()


In [9]:
CSR.data#value

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8], dtype=int32)

In [10]:
col = CSR.indices
CSR.indices

array([1, 4, 2, 3, 5, 7, 5, 6, 2, 7, 8, 8, 9], dtype=int32)

In [11]:
index = CSR.indptr
CSR.indptr

array([ 0,  2,  3,  6,  8, 10, 11, 11, 12, 13, 13, 13, 13, 13],
      dtype=int32)

In [12]:
# python-TypeError: write() argument must be str, not numpy.float64
# 错误前
# f.write(data_y[i])
# 错误后
# f.write(str(data_y[i]))

fl=open('E:\\研一下学期资料\\CPE800\\It_can_work\\COO_text_to_CSR_text.txt', 'w')
for i in CSR.data:
    fl.write(str(i))
    fl.write(" ")
    
fl.write("\n")

for i in col:
    fl.write(str(i))
    fl.write(" ")
    
fl.write("\n")
for i in index:
    fl.write(str(i))
    fl.write(" ")
    
fl.close()

In [13]:
def BFS(col, index):
    visited = [0]; output = []; current_id = 0
    while visited:
        current = visited.pop(0)
        num_of_element = index[current_id+1]-index[current_id]
        for i in range(num_of_element):
            visited.append(col[i+current_id])
            temp = [current,col[i+current_id]]
            print(temp)
            if temp not in output:
                output.append(temp)
                ## has BUG need to be fix

        current_id = col[c]


    return output


In [14]:
A = CSR
G = nx.DiGraph(A)       # directed because A need not be symmetric
paths = nx.all_pairs_shortest_path_length(G)
indices = []
indptr = [0]
for row in paths:
  reachable = [v for v in row[1] if row[1][v] > 0]
  indices.extend(reachable)
  indptr.append(len(indices))
data = np.ones((len(indices),), dtype=np.uint8)

for i in range(len(data)):
    data[i] = 8

A_trans =sparse.csr_matrix((data, indices, indptr), shape=A.shape)
print(A, "\n\n",A,"\n", A_trans)

  (0, 1)	8
  (0, 4)	8
  (1, 2)	8
  (2, 3)	8
  (2, 5)	8
  (2, 7)	8
  (3, 5)	8
  (3, 6)	8
  (4, 2)	8
  (4, 7)	8
  (5, 8)	8
  (7, 8)	8
  (8, 9)	8 

   (0, 1)	8
  (0, 4)	8
  (1, 2)	8
  (2, 3)	8
  (2, 5)	8
  (2, 7)	8
  (3, 5)	8
  (3, 6)	8
  (4, 2)	8
  (4, 7)	8
  (5, 8)	8
  (7, 8)	8
  (8, 9)	8 
   (0, 1)	8
  (0, 4)	8
  (0, 2)	8
  (0, 7)	8
  (0, 3)	8
  (0, 5)	8
  (0, 8)	8
  (0, 6)	8
  (0, 9)	8
  (1, 2)	8
  (1, 3)	8
  (1, 5)	8
  (1, 7)	8
  (1, 6)	8
  (1, 8)	8
  (1, 9)	8
  (2, 3)	8
  (2, 5)	8
  (2, 7)	8
  (2, 6)	8
  (2, 8)	8
  (2, 9)	8
  (3, 5)	8
  (3, 6)	8
  (3, 8)	8
  (3, 9)	8
  (4, 2)	8
  (4, 7)	8
  (4, 3)	8
  (4, 5)	8
  (4, 8)	8
  (4, 6)	8
  (4, 9)	8
  (5, 8)	8
  (5, 9)	8
  (7, 8)	8
  (7, 9)	8
  (8, 9)	8


In [16]:
print(data)

[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8
 8]


In [17]:
print("Original data using toy.dat")
print(A)
print("DENS—format")
print(origional)
print("")
print("CSR—format")
print("Value:",CSR.data)
print("Col:",CSR.indices)
print("Index:",CSR.indptr)
print("")
print("Result:")
print(A_trans)

Original data using toy.dat
  (0, 1)	8
  (0, 4)	8
  (1, 2)	8
  (2, 3)	8
  (2, 5)	8
  (2, 7)	8
  (3, 5)	8
  (3, 6)	8
  (4, 2)	8
  (4, 7)	8
  (5, 8)	8
  (7, 8)	8
  (8, 9)	8
DENS—format
[[0 8 0 0 8 0 0 0 0 0 0 0 0]
 [0 0 8 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 8 0 8 0 8 0 0 0 0 0]
 [0 0 0 0 0 8 8 0 0 0 0 0 0]
 [0 0 8 0 0 0 0 8 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 8 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 8 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 8 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]

CSR—format
Value: [8 8 8 8 8 8 8 8 8 8 8 8 8]
Col: [1 4 2 3 5 7 5 6 2 7 8 8 9]
Index: [ 0  2  3  6  8 10 11 11 12 13 13 13 13 13]

Result:
  (0, 1)	8
  (0, 4)	8
  (0, 2)	8
  (0, 7)	8
  (0, 3)	8
  (0, 5)	8
  (0, 8)	8
  (0, 6)	8
  (0, 9)	8
  (1, 2)	8
  (1, 3)	8
  (1, 5)	8
  (1, 7)	8
  (1, 6)	8
  (1, 8)	8
  (1, 9)	8
  (2, 3)	8
  (2, 5)	8
  (2, 7)	8
  (2, 6)	8
  (2, 8)	8
  (2, 9)	8
  (3, 5)	8
  (3, 6)	8
  (3, 8)	8
  (3, 9)	8
  (4, 2)	8
  

In [25]:
aaa=[1, 4, 2, 3, 5, 7, 5, 6, 2, 7, 8, 8, 9]
bb=aaa[::-1] 
bb.index(8)
target=8

1

In [29]:
target=8
aaa[len(aaa)-1-aaa[::-1] .index(target)]

8